name: docker

on:
  # workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 0 * * 0"

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        base-image-tag:
          - bionic
          - buster
        llvm-version:
          - 15.0.1
          - 14.0.6
          - 13.0.1
          - 12.0.1
          - 11.1.0
    env:
      PLATFORMS: linux/amd64
      BINUTILS_VERSION: 2.39
      CMAKE_VERSION: 3.24.2
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "BASE_IMAGE_TAG=${{ matrix.base-image-tag }}" | tee -a "$GITHUB_ENV"
          echo "LLVM_VERSION=${{ matrix.llvm-version }}" | tee -a "$GITHUB_ENV"
          echo "LLVM_VERSION_MAJOR=$(echo "${{ matrix.llvm-version }}" | cut -d '.' -f 1)" | tee -a "$GITHUB_ENV"
          echo "LLVM_VERSION_MINOR=$(echo "${{ matrix.llvm-version }}" | cut -d '.' -f 2)" | tee -a "$GITHUB_ENV"
          echo "LLVM_VERSION_REVISION=$(echo "${{ matrix.llvm-version }}" | cut -d '.' -f 3)" | tee -a "$GITHUB_ENV"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
            BINUTILS_VERSION=${{ env.BINUTILS_VERSION }}
            CMAKE_VERSION=${{ env.CMAKE_VERSION }}
            LLVM_VERSION=${{ env.LLVM_VERSION }}
          outputs: type=tar,dest=llvm-${{ env.LLVM_VERSION }}-${{ env.BASE_IMAGE_TAG }}.tar
      - uses: actions/upload-artifact@v3
        with:
          name: llvm-${{ env.LLVM_VERSION }}-${{ env.BASE_IMAGE_TAG }}
          path: llvm-${{ env.LLVM_VERSION }}-${{ env.BASE_IMAGE_TAG }}.tar
